### ISSUE TITLE
Keine Seitenzahlen auf Kapitel-Startseiten

### ISSUE THREAD

**Issue by ponchofiesta** [a-czyrny/LaTeX-Master-Vorlage#5]
Eine tolle Vorlage. Ich nutze sie gerade für meine Bachelorarbeit. Mir ist dabei aber aufgefallen, dass auf Seiten, auf denen ein Kapitel startet, keine Seitenzahlen angezeigt werden. Das sollte doch eigentlich nicht so sein oder? Kann man das irgendwie korrigieren?

**Comment by ponchofiesta** [comment]
Falls jemand auch darüber stolpert. Ich habe in der *settings.tex* den `\ohead`-Befehl entsprechend abgeändert um die Seitenzahl auch auf Kapitel-Startseiten zu bekommen:
```latex
\ohead[\thepage]{\thepage}
```

**Comment by a-czyrny** [comment]
Hallo ponchofiesta,

ich habe mich bei den Kapitelseiten an gängigen Büchern orientiert, die dort häufig auch keine Seitenzahl zeigen. Schau doch einfach in wissenschaftliche Werke, dann wirst du sehen dass dies so ist. Bei Bedarf kann man die Seitenzahlen, wie beschrieben, auch einblenden.

**Comment by ponchofiesta** [comment]
Übrigens: Ich hatte die Frage auch auf Stackoverflow gestellt und eine sehr ausführliche Antwort bekommen. Es wurde ein anderer Weg empfohlen, den ich hier nicht vorenthalten will:

```latex
\usepackage[automark,headsepline]{scrlayer-scrpage}% sets page style scrheadings automatically
\clearpairofpagestyles
\ihead{\leftmark}
\ohead*{\pagemark}
\setkomafont{pagenumber}{}% default is \normalfont\normalcolor
```

@a-czyrny 
Ich habe nach deiner Antwort extra mal meine Beispiel-Arbeiten (Bachelor, Master und Diplom) sowie drei Fachbücher durchgeschaut. Alle hatten durchweg Seitenzahlen auf den Kapitel-Startseiten - allerdings nicht unbedingt an der selben Position. Alternativ wird dann mal von oben rechts nach unten zentriert gewechselt. Ansonsten weiß ich nicht, was du mit wissenschaftlichen Arbeiten vielleicht sonst meinen könntest. Papers sind eh ganz anders aufgebaut. Das soll auch kein Angriff sein - es kann ja jeder machen, wie er es für richtig hält. Ich will nur anderen sagen, dass es mit Sicherheit nicht der generelle Standard ist. Ansonsten trotzdem nochmals der Dank für diese tolle Vorlage!

**Comment by a-czyrny** [comment]
Dein Hinweis und die alternative Formatierung finde ich gut. Die Kritik deinerseits ist richtig und hilft Anderen, die sich hier eine Nummerierung wünschen, diese elegant einzufügen. Am Ende kommt es doch darauf an was dein Erst-/Zweitprüfer für ein Layout wünschen oder die UNI/Hochschule an Formatierung vorgeben.

**Comment by a-czyrny** [comment]
Ergänzend hatte ich be "overleaf" eine Neue strukturierte Variante angelegt: 

https://www.overleaf.com/project/58ff68dbe750871a7e4933ca

und dort beispielhaft bei der erste Kapitelseite rechts unten die Nummerierung eingeführt.
